// Indie. The format: core/grooves.js's header.
export default `
style indie  Indie
blurb   dance-punk hats over four on the floor, floor-tom beats, a loose garage backbeat
tempo   100-150
feel    straight, driving, four on the floor
swing   none
lay     snare +2  hat -2
human   6ms 8%
kit     acoustic room .45 tone .1
studio  Maple 70s

intro   Floor toms  1 bar
  floor  x.x. x.x. x.x. x.x.
  tom2   .... .... .... ..x.
  kick   X... X... X... X...

verse   Dance-punk  1 bar
  hat    x... x... x... x...
  open   ..x. ..x. ..x. ..x.
  snare  .... X... .... X...
  kick   X... X... X... X...

verse   Garage  1 bar
  hat    x.x. x.x. x.x. x.x.
  snare  .... X... .... X...
  kick   X... ..x. ..x. ....

chorus  Ride and floor  1 bar
  ride   x.x. x.x. x.x. x.x.
  floor  ..x. .... ..x. ....
  snare  .... X... .... X...
  kick   X... X... X... X...

bridge  Toms only  1 bar
  tom1   x... .... x... ....
  floor  ..x. x.x. ..x. x.xx
  kick   X... ..x. X... ..x.

half    Half-time  1 bar
  feel   half-time
  hat    x.x. x.x. x.x. x.x.
  open   .... .... .... ..x.
  snare  .... .... X... ....
  kick   X... .... ..x. ....

fill    Snare pickup  1 beat
  snare  .xxX

fill    Floor tom rumble  2 beats
  floor  xxxx xxxX
  kick   x... x...

fill    Toms down  1 bar
  snare  xxxx .... .... ....
  tom1   .... xxxx .... ....
  tom2   .... .... xxxx ....
  floor  .... .... .... xxxX
  kick   x... x... x... x...

ending  One more hit  2 bars
  hat    x... x... x... .... | .... .... .... ....
  open   ..x. ..x. ..x. .... | .... .... .... ....
  snare  .... X... .... xxxX | .... .... .... ....
  crash  .... .... .... .... | X... .... .... ....
  kick   X... X... X... X... | X... .... .... ....
`;
