// @ts-check
// Modern metal. The format: core/grooves.js's header. The kick locked to a syncopated, palm-muted riff (djent unison)
// over a steady hat, half-time China breakdowns, double-kick gallops, a bar of silence before the breakdown, and
// choruses ridden on the crash or the China. Written for Studio A's note map; `kit metal` plays it on Rusty Sticks
// where the studio has it.
export default `
style modernmetal  Modern metal
blurb   djent unison kicks under a steady hat, half-time China breakdowns, gallops, and open choruses on the crash
tempo   90-160
feel    syncopated, heavy, half-time, djent
swing   none
lay     hat -2  kick -1
human   2ms 4%
kit     metal
studio  Arena

intro   Crash and floor toms  1 bar
  crash  X... .... .... ....
  floor  x.x. x.x. x.x. x.x.
  tom3   .... .... ..x. x.x.
  kick   x... x... x... x...

verse   Djent unison  1 bar
  feel   syncopated, djent, half-time
  hat    x.x. x.x. x.x. x.x.
  snare  .... .... X... ....
  kick   x..x ..x. .x.. x.x.

verse   Djent unison, quarters on the hat  1 bar
  feel   syncopated, djent
  hat    x... x... x... x...
  snare  .... X... .... X...
  kick   x.x. .xx. x..x .x.x

verse   Djent unison in threes  2 bars
  feel   syncopated, djent, polyrhythm, half-time
  hat    x... x... x... x... | x... x... x... x...
  snare  .... .... X... .... | .... .... X... ....
  kick   x..x ..x. .x.. x..x | ..x. .x.. x..x ..x.

verse   Double-kick gallop  1 bar
  ride   x.x. x.x. x.x. x.x.
  snare  .... X... .... X...
  kick   x.xx x.xx x.xx x.xx

chorus  Open chorus, crash riding  1 bar
  crash  x.x. x.x. x.x. x.x.
  snare  .... X... .... X...
  kick   x.x. x.x. x.x. x.x.

chorus  China on the beat, kick in bursts  1 bar
  china  X... x... X... x...
  snare  .... X... .... X...
  kick   xxxx x.x. xxxx x.x.

half    Half-time China breakdown  1 bar
  feel   half-time, breakdown, heavy
  china  x... x... x... x...
  snare  .... .... X... ....
  kick   X.xx .... .xx. x...

half    Half-time China breakdown, stopping  2 bars
  feel   half-time, breakdown, heavy
  china  X... .... x... .... | X... .... x... ....
  snare  .... .... X... .... | .... .... X... ....
  kick   Xx.x x... ..xx .x.. | X..x .x.. x... ....

fill    Drop: one stab, then a bar of silence  1 bar
  feel   drop, silence, stop, before the breakdown
  snare  X... .... .... ....
  kick   X... .... .... ....

bridge  Tom groove under the riff  1 bar
  ride   x... x... x... x...
  tom1   x... .... .... ....
  floor  ..x. x.x. ..x. x.x.
  snare  .... X... .... X...
  kick   x..x ..x. x..x ..x.

fill    Kick and snare flurry  1 beat
  snare  x.x.
  kick   .x.x

fill    Toms down, feet under  2 beats
  tom1   xx.. ....
  tom3   ..xx ....
  floor  .... xxxX
  kick   xxxx xxxx

fill    Round the kit into the drop  1 bar
  snare  xxxx .... .... ....
  tom1   .... xxxx .... ....
  tom3   .... .... xxxx ....
  floor  .... .... .... xxxX
  kick   x.x. x.x. x.x. xxxx

ending  Crash out  2 bars
  crash  X... .... X... .... | X... .... .... ....
  china  .... .... X... .... | .... .... .... ....
  snare  .... X... X... .... | X... .... .... ....
  kick   X.xx .xx. X... .... | X... .... .... ....
`;
