// Reggae. The format: core/grooves.js's header. The one drop: nothing on one, kick and cross-stick on three.
export default `
style reggae  Reggae
blurb   the one drop: kick and cross-stick together on three, nothing on the one, swung hats; steppers in the chorus
tempo   64-92
feel    one drop, swung, laid back
swing   8 64-58%
lay     stick +10  snare +10  kick +6
human   5ms 8%
kit     acoustic room .3 tone -.1
studio  Dead 70s

intro   Hats and rim  1 bar
  hat    x.x. x.x. x.x. x.x.
  stick  .... .... X... ....

verse   One drop  1 bar
  hat    x.x. x.x. x.x. x.x.
  stick  .... .... X... ....
  kick   .... .... X... ....

verse   One drop, ghosts  2 bars
  hat    x.x. x.x. x.x. x.x. | x.x. x.x. x.x. x.xx
  stick  .... .... X... .... | .... .... X... ....
  snare  .... ..o. .... .... | .... .... .... ..o.
  kick   .... .... X... .... | .... .... X... ....

chorus  Steppers  1 bar
  hat    x.x. x.x. x.x. x.x.
  snare  .... .... X... ....
  kick   X... X... X... X...

bridge  Rockers  1 bar
  hat    x.x. x.x. x.x. x.x.
  snare  .... .... X... ....
  kick   X... .... X... ....

fill    Flam  1 beat
  snare  ..F.

fill    Tom flams  2 beats
  tom1   f... ....
  tom2   ..f. ....
  floor  .... F...

fill    Roll to the drop  1 bar
  snare  .... .... oxox xxxX
  tom1   f... .... .... ....
  floor  .... F... .... ....
  kick   .... .... X... ....

ending  Last drop  2 bars
  hat    x.x. x.x. x.x. .... | .... .... .... ....
  stick  .... .... X... .... | .... .... .... ....
  snare  .... .... .... oxxX | .... .... .... ....
  crash  .... .... .... .... | X... .... .... ....
  kick   .... .... X... .... | X... .... .... ....
`;
